import React from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { formatNumber } from "@/lib/game-config";
import { useGame, type Mission } from "@/lib/game-store";

const cadenceColors = { Diarias: "#9b8cff", Semanales: "#70e1bd", Mensuales: "#ffd477" } as const;

function MissionCard({ mission, onClaim }: { mission: Mission; onClaim: () => void }) {
  const ratio = Math.min(1, mission.progress / mission.goal);
  const ready = ratio >= 1 && !mission.claimed;
  return <View style={styles.card}><View style={styles.cardHeader}><View style={[styles.cadence, { backgroundColor: `${cadenceColors[mission.cadence]}22` }]}><Text style={[styles.cadenceText, { color: cadenceColors[mission.cadence] }]}>{mission.cadence}</Text></View>{mission.claimed ? <Text style={styles.claimed}>COMPLETADA</Text> : <Text style={styles.progress}>{formatNumber(mission.progress)} / {formatNumber(mission.goal)}</Text>}</View><Text style={styles.missionTitle}>{mission.title}</Text><Text style={styles.description}>{mission.description}</Text><View style={styles.track}><View style={[styles.fill, { width: `${Math.max(ratio * 100, 2)}%`, backgroundColor: cadenceColors[mission.cadence] }]} /></View><View style={styles.footer}><Text style={styles.reward}>{mission.reward.pkc ? `● ${mission.reward.pkc} PKC` : ""}{mission.reward.pkd ? `  ◆ ${mission.reward.pkd} PKD` : ""}{mission.reward.item ? `  ◇ ${mission.reward.item}` : ""}</Text>{ready && <Pressable onPress={onClaim} style={({ pressed }) => [styles.claimButton, pressed && styles.pressed]}><Text style={styles.claimText}>Reclamar</Text></Pressable>}</View></View>;
}

export default function QuestsScreen() {
  const { state, claimMission } = useGame();
  const completed = state.missions.filter((mission) => mission.claimed).length;
  const claim = (id: string) => { const result = claimMission(id); Alert.alert(result.ok ? "Recompensa recibida" : "Misión pendiente", result.message); };
  return <View style={styles.screen}><FlatList data={state.missions} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<><Text style={styles.eyebrow}>MISIONES / OBJETIVOS</Text><Text style={styles.title}>Pequeños pasos, grandes ritmos</Text><Text style={styles.subtitle}>Completa actividades para conseguir PKC, PKD y objetos sin compras con dinero real.</Text><View style={styles.overview}><View><Text style={styles.overviewLabel}>PROGRESO DEL CICLO</Text><Text style={styles.overviewValue}>{completed} / {state.missions.length}</Text></View><Text style={styles.overviewIcon}>⚑</Text></View><Text style={styles.sectionTitle}>Tus misiones</Text></>} renderItem={({ item }) => <MissionCard mission={item} onClaim={() => claim(item.id)} />} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} ListFooterComponent={<View style={styles.footerNote}><Text style={styles.footerNoteTitle}>Recompensas justas</Text><Text style={styles.footerNoteText}>Todo se obtiene jugando: no hay microtransacciones, anuncios obligatorios ni loot boxes de pago.</Text></View>} />;</View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#0d0b1b" }, content: { padding: 20, paddingTop: 18, paddingBottom: 32 }, eyebrow: { color: "#8f87b1", fontSize: 10, letterSpacing: 1.8, fontWeight: "800" }, title: { color: "#f7f4ff", fontSize: 25, lineHeight: 30, fontWeight: "900", marginTop: 7 }, subtitle: { color: "#a9a3c8", fontSize: 12, lineHeight: 18, marginTop: 8 }, overview: { marginTop: 21, backgroundColor: "#211d38", borderWidth: 1, borderColor: "#38305d", borderRadius: 18, padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, overviewLabel: { color: "#8f87b1", fontSize: 10, letterSpacing: 1.2, fontWeight: "800" }, overviewValue: { color: "#f7f4ff", fontSize: 28, fontWeight: "900", marginTop: 5 }, overviewIcon: { color: "#ffd477", fontSize: 35 }, sectionTitle: { color: "#f7f4ff", fontSize: 16, fontWeight: "900", marginTop: 24, marginBottom: 11 }, card: { backgroundColor: "#17132c", borderWidth: 1, borderColor: "#312b53", borderRadius: 17, padding: 14 }, cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, cadence: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5 }, cadenceText: { fontSize: 9, fontWeight: "900", letterSpacing: 0.5 }, progress: { color: "#a9a3c8", fontSize: 10, fontWeight: "800" }, claimed: { color: "#70e1bd", fontSize: 9, letterSpacing: 0.7, fontWeight: "900" }, missionTitle: { color: "#f7f4ff", fontSize: 14, fontWeight: "900", marginTop: 14 }, description: { color: "#a9a3c8", fontSize: 11, marginTop: 3 }, track: { height: 7, backgroundColor: "#30294c", borderRadius: 5, marginTop: 15, overflow: "hidden" }, fill: { height: "100%", borderRadius: 5 }, footer: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 13 }, reward: { color: "#d6ceff", fontSize: 10, fontWeight: "800", flex: 1 }, claimButton: { backgroundColor: "#9b8cff", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8 }, claimText: { color: "#16122d", fontSize: 10, fontWeight: "900" }, pressed: { opacity: 0.75, transform: [{ scale: 0.98 }] }, footerNote: { backgroundColor: "#1c3e3b", borderRadius: 15, padding: 13, marginTop: 20 }, footerNoteTitle: { color: "#70e1bd", fontWeight: "900", fontSize: 12 }, footerNoteText: { color: "#b8e8d6", fontSize: 10, lineHeight: 15, marginTop: 5 },
});
